"""

Common Emotions: (generated by ChatGPT)
1. Stressed - "I failed my exam."
2. Celebratory - "I'm looking forward to going to the party."
3. Lazy - "I want to stay in my dorm and watch a movie."
4. Hungry - "I haven't eaten all day."
5. Social - "I want to hang out with friends."
6. Healthy - "I'm trying to eat clean and stay fit."
7. Comfort - "I need some comfort food."
8. Adventurous - "I want to try something new."
9. Focused - "I need something quick and easy because I have to study."
10. Budget-conscious - "I need something affordable."

"""

EMOTIONS = {"Stressed", "Celebratory", "Lazy", "Hungry", "Social", "Healthy", "Comfort", "Adventurous", "Focused", "Budget-conscious"}

from openai import OpenAI
from dotenv import load_dotenv

def get_emotion(user_input): 
    load_dotenv()       
    client = OpenAI()

    content = f"Here is how I'm feeling: {user_input}. Which of these emotions ({EMOTIONS}) am I feeling? Choose the emotion that best describes how I'm feeling. Just give me the name of the emotion, no fluff."
    stream = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": content}],
        stream=True,
    )

    output = ""
    for chunk in stream:
        if chunk.choices[0].delta.content is not None:
            output += chunk.choices[0].delta.content

    return output