"""

Common Emotions: (generated by ChatGPT)
1. Casual - For relaxed, neutral, or indifferent feelings.
2. Healthy - For health-conscious or revitalized moods.
3. Content - For satisfied, pleasant, or happy feelings.
4. Social - For cheerful, social, or celebratory moods.
5. Comfort - For craving or comfort food desires.
6. Adventurous - For curious or adventurous feelings.
7. Productive - For focused or in need of a pick-me-up moods.
8. Excited - For excited or lively feelings.
9. Relaxed - For relaxed or content moods.
10. Quick - For in a rush or quick meal needs.

"""

from textblob import TextBlob

def get_emotion(user_input):        
    blob = TextBlob(user_input)
    polarity = blob.sentiment.polarity # -1 to 1

    if polarity > 0:
        return "positive"
    elif polarity < 0:
        return "negative"
    else:
        return "neutral"
