"""

Common Emotions: (generated by ChatGPT)
1. Stressed - After exams or assignments, students may want comfort food or a relaxing spot.
2. Adventurous - Feeling curious and wanting to try something new or different.
3. Tired - Craving something quick, easy, or delivered, especially after a long day.
4. Excited - Looking for a celebratory meal, possibly for an achievement or special occasion.
5. Sad - Wanting something comforting or familiar to improve their mood.
6. Romantic - Seeking a place with a cozy or intimate ambiance for a date.
7. Social - Looking for a place to hang out with friends, often casual and lively.
8. Hungry - Just plain starving and in need of something filling and satisfying.
9. Bored - Wanting a place that offers more than just food, maybe a unique dining experience.
10. Healthy - Looking for nutritious or lighter meal options, possibly after working out or as part of a diet.
11. Affordable - Wanting a place that offers good value for the price, often for students or budget-conscious diners.

"""

EMOTIONS = {"Stressed", "Adventurous", "Tired", "Excited", "Sad", "Romantic", "Social", "Hungry", "Bored", "Healthy", "Affordable"}

from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()       
client = OpenAI()

def get_emotion(user_input): 
    content = f"Here is how I'm feeling: {user_input}. Which of these emotions ({EMOTIONS}) am I feeling? Choose the emotion that best describes how I'm feeling. Just give me the name of the emotion, no fluff."
    stream = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": content}],
        stream=True,
    )

    output = ""
    for chunk in stream:
        if chunk.choices[0].delta.content is not None:
            output += chunk.choices[0].delta.content

    return output

def __main__():
    print(get_emotion("I think I failed my exam!"))

if __name__ == '__main__':
    __main__()